name: Laravel CI & Test

on:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master , dev ]

jobs:
  build-js:
    name: Build Static Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn Build
        run: |
          yarn install
          yarn prod
          cat public/mix-manifest.json # See asset versions in log
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public

  test-laravel:
    name: Test Laravel API
    runs-on: ubuntu-latest

    needs: build-js

    services:
      pgsql:
        image: postgres:13
        ports:
          - 5432
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379

      mailhog:
        image: mailhog/mailhog:latest
        ports:
          - 1025
          - 8025

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run tests via PHPUnit -- MTFBWY !
      run: |
        echo 'May the force be with the test !'
        echo ''
        vendor/bin/phpunit

